services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-hukum-id
    env_file:
      - .env
    ports:
      - "8501:8501"
    volumes:
      - chroma_data:/app/chroma_db
    restart: unless-stopped

volumes:
  chroma_data: